version: "3.9"
services:
  app:
    build: .
    env_file: .env               # 秘匿値はここで注入
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app           # ホットリロード用
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: