version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nolang-bot:latest
    ports:
      - "3000:3000"
    volumes:
      - .:/home/user/nolang-bot        # ホットリロード用
      - ~/.gitconfig:/home/user/.gitconfig:ro
    command: /bin/bash           # 開発用にbashを起動
    stdin_open: true             # docker run -i
    tty: true                    # docker run -t